apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-nodepool
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/yeongki0944/demo-eks-gitops.git  # ★ 변경
    targetRevision: main
    path: charts/karpenter
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
